import Head from 'next/head'
import Image from 'next/image'
import { AspectRatio } from '../components/AspectRatio'
import { Box } from '../components/Box'
import { Button } from '../components/Button'
import { Flex } from '../components/Flex'
import { InputGroup } from '../components/InputGroup'
import { Table } from '../components/Table'
import { Text } from '../components/Text'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Flex direction="row" align="center">
          <Box sx={{
            width: "200px"
          }}>
            <AspectRatio>
              <Text size="3">Coba</Text>
            </AspectRatio>
          </Box>
        </Flex>
        <Table>
          <Table.Head>
            <Table.TH>
              <Table.TR>A</Table.TR>
            </Table.TH>
          </Table.Head>
        </Table>
        <Box>
          <Text as="h3">Button Variant</Text>
          <Button>Button</Button>
          <Button intent="primary">Primary</Button>
          <Button intent="secondary">Secondary</Button>
          <Button intent="success">Success</Button>
          <Button intent="danger">Danger</Button>
          <Button intent="warning">Warning</Button>
          <Button intent="link">Link</Button>
          <Text as="h3">Outlined Variant</Text>
          <Button outlined={true}>Button</Button>
          <Button intent="primary" outlined={true}>Primary</Button>
          <Button intent="secondary" outlined={true}>Secondary</Button>
          <Button intent="success" outlined={true}>Success</Button>
          <Button intent="danger" outlined={true}>Danger</Button>
          <Button intent="warning" outlined={true}>Warning</Button>
        </Box>
        <InputGroup />
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Get started by editing{' '}
          <code>pages/index.js</code>
        </p>

        <div>
          <a href="https://nextjs.org/docs">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/canary/examples">
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
